# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11game_status.proto\"4\n\nGameStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x05nones\x18\x03 \x03(\x0b\x32\t.HostNode\"B\n\x08HostNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x1a\n\x05\x66iles\x18\x03 \x01(\x0b\x32\x0b.TreeSystem\"\xa4\x01\n\nTreeSystem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.FileType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x18\n\x03sub\x18\x04 \x03(\x0b\x32\x0b.TreeSystem\x12\x10\n\x08readable\x18\x05 \x01(\x08\x12\x10\n\x08writable\x18\x06 \x01(\x08\x12\x12\n\nexecutable\x18\x07 \x01(\x08\x12\x0f\n\x07visible\x18\x08 \x01(\x08*@\n\x08\x46ileType\x12\x07\n\x03\x64ir\x10\x00\x12\x07\n\x03img\x10\x01\x12\x07\n\x03txt\x10\x02\x12\x07\n\x03\x65xe\x10\x03\x12\x07\n\x03\x62in\x10\x04\x12\x07\n\x03\x65nc\x10\x05\x62\x06proto3')

_FILETYPE = DESCRIPTOR.enum_types_by_name['FileType']
FileType = enum_type_wrapper.EnumTypeWrapper(_FILETYPE)
dir = 0
img = 1
txt = 2
exe = 3
bin = 4
enc = 5


_GAMESTATUS = DESCRIPTOR.message_types_by_name['GameStatus']
_HOSTNODE = DESCRIPTOR.message_types_by_name['HostNode']
_TREESYSTEM = DESCRIPTOR.message_types_by_name['TreeSystem']
GameStatus = _reflection.GeneratedProtocolMessageType('GameStatus', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUS,
  '__module__' : 'game_status_pb2'
  # @@protoc_insertion_point(class_scope:GameStatus)
  })
_sym_db.RegisterMessage(GameStatus)

HostNode = _reflection.GeneratedProtocolMessageType('HostNode', (_message.Message,), {
  'DESCRIPTOR' : _HOSTNODE,
  '__module__' : 'game_status_pb2'
  # @@protoc_insertion_point(class_scope:HostNode)
  })
_sym_db.RegisterMessage(HostNode)

TreeSystem = _reflection.GeneratedProtocolMessageType('TreeSystem', (_message.Message,), {
  'DESCRIPTOR' : _TREESYSTEM,
  '__module__' : 'game_status_pb2'
  # @@protoc_insertion_point(class_scope:TreeSystem)
  })
_sym_db.RegisterMessage(TreeSystem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILETYPE._serialized_start=310
  _FILETYPE._serialized_end=374
  _GAMESTATUS._serialized_start=21
  _GAMESTATUS._serialized_end=73
  _HOSTNODE._serialized_start=75
  _HOSTNODE._serialized_end=141
  _TREESYSTEM._serialized_start=144
  _TREESYSTEM._serialized_end=308
# @@protoc_insertion_point(module_scope)
