# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/game_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/game_status.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14pb/game_status.proto\"4\n\nGameStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x05nones\x18\x03 \x03(\x0b\x32\t.HostNode\"B\n\x08HostNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x1a\n\x05\x66iles\x18\x03 \x01(\x0b\x32\x0b.TreeSystem\"\xa4\x01\n\nTreeSystem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x04type\x18\x02 \x01(\x0e\x32\t.FileType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x18\n\x03sub\x18\x04 \x03(\x0b\x32\x0b.TreeSystem\x12\x10\n\x08readable\x18\x05 \x01(\x08\x12\x10\n\x08writable\x18\x06 \x01(\x08\x12\x12\n\nexecutable\x18\x07 \x01(\x08\x12\x0f\n\x07visible\x18\x08 \x01(\x08*@\n\x08\x46ileType\x12\x07\n\x03\x64ir\x10\x00\x12\x07\n\x03img\x10\x01\x12\x07\n\x03txt\x10\x02\x12\x07\n\x03\x65xe\x10\x03\x12\x07\n\x03\x62in\x10\x04\x12\x07\n\x03\x65nc\x10\x05\x62\x06proto3'
)

_FILETYPE = _descriptor.EnumDescriptor(
  name='FileType',
  full_name='FileType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='dir', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='img', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='txt', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='exe', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='bin', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='enc', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=313,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_FILETYPE)

FileType = enum_type_wrapper.EnumTypeWrapper(_FILETYPE)
dir = 0
img = 1
txt = 2
exe = 3
bin = 4
enc = 5



_GAMESTATUS = _descriptor.Descriptor(
  name='GameStatus',
  full_name='GameStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GameStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nones', full_name='GameStatus.nones', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=76,
)


_HOSTNODE = _descriptor.Descriptor(
  name='HostNode',
  full_name='HostNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HostNode.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='host', full_name='HostNode.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='files', full_name='HostNode.files', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=144,
)


_TREESYSTEM = _descriptor.Descriptor(
  name='TreeSystem',
  full_name='TreeSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TreeSystem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='TreeSystem.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='TreeSystem.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub', full_name='TreeSystem.sub', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='readable', full_name='TreeSystem.readable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='writable', full_name='TreeSystem.writable', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executable', full_name='TreeSystem.executable', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visible', full_name='TreeSystem.visible', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=311,
)

_GAMESTATUS.fields_by_name['nones'].message_type = _HOSTNODE
_HOSTNODE.fields_by_name['files'].message_type = _TREESYSTEM
_TREESYSTEM.fields_by_name['type'].enum_type = _FILETYPE
_TREESYSTEM.fields_by_name['sub'].message_type = _TREESYSTEM
DESCRIPTOR.message_types_by_name['GameStatus'] = _GAMESTATUS
DESCRIPTOR.message_types_by_name['HostNode'] = _HOSTNODE
DESCRIPTOR.message_types_by_name['TreeSystem'] = _TREESYSTEM
DESCRIPTOR.enum_types_by_name['FileType'] = _FILETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameStatus = _reflection.GeneratedProtocolMessageType('GameStatus', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATUS,
  '__module__' : 'pb.game_status_pb2'
  # @@protoc_insertion_point(class_scope:GameStatus)
  })
_sym_db.RegisterMessage(GameStatus)

HostNode = _reflection.GeneratedProtocolMessageType('HostNode', (_message.Message,), {
  'DESCRIPTOR' : _HOSTNODE,
  '__module__' : 'pb.game_status_pb2'
  # @@protoc_insertion_point(class_scope:HostNode)
  })
_sym_db.RegisterMessage(HostNode)

TreeSystem = _reflection.GeneratedProtocolMessageType('TreeSystem', (_message.Message,), {
  'DESCRIPTOR' : _TREESYSTEM,
  '__module__' : 'pb.game_status_pb2'
  # @@protoc_insertion_point(class_scope:TreeSystem)
  })
_sym_db.RegisterMessage(TreeSystem)


# @@protoc_insertion_point(module_scope)
